### ISSUE TITLE
there isnt anything

### ISSUE THREAD

**Issue by gabrielmaster123** [ParticulaCode/GoCubeAPI#1]
if the API exist can you tell me some third party apps

**Comment by AshleyF** [comment]
FYI, it has been reverse engineered. See:
* http://briefcubing.com
* http://cubeast.com
* https://bluetooth.cubing.net
Source:
* https://github.com/AshleyF/briefcubing/blob/master/btcube.js
* https://github.com/cubing/cuble.js

**Comment by gabrielmaster123** [comment]
is there a third party app that help you learn oll and pll?

**Comment by AshleyF** [comment]
That’s exactly what briefcubing.com is for :)
https://youtu.be/ujNmxmBQT7Q (demo using Giiker cube, but works with GoCube and others also)

**Comment by gabrielmaster123** [comment]
Thanks I couldnt test it because I didnt have chrome

**Comment by gabrielmaster123** [comment]
I managed to get the official API if you are interested.
https://drive.google.com/file/d/1dnSkhPyyf0aI46Z-89KXgUi2nttpAb6q/view

**Comment by gabrielmaster123** [comment]
[image: image.png]from this email
